apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: xxxxxx
      containers:
        - name: my-app
          image: my-app:latest
          ports:
            - name: http
              containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: ENV_VAR
              value: foobar
