apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: my-giphy-deployment
  labels:
    app: my-giphy-deployment
spec:
  selector:
    matchLabels:
      app: my-giphy
  template:
    metadata:
      labels:
        app: my-giphy
    spec:
      restartPolicy: Always
      containers:
        - name: my-giphy
          image: lhdang88/giphy-demo:latest
          ports:
            - name: http
              containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: ENV_VAR
              value: foobar
