apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  loadBalancerIP: 11.111.11.11
  selector:
    app: my-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: "LoadBalancer"
